package cc.minis.image2studio;

import android.app.*;import android.os.*;import android.provider.MediaStore;import android.content.*;import android.net.*;import android.graphics.*;import android.util.Base64;import android.webkit.*;import android.widget.*;import android.view.*;import org.json.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 static final int REQ_PICK=77;static final String DEF_BASE="https://factory.pub",DEF_MODEL="gpt-image-2";WebView web;SharedPreferences sp;ArrayList<Uri> selectedUris=new ArrayList<Uri>();ArrayList<String> currentPaths=new ArrayList<String>();
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("image2studio",MODE_PRIVATE);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);web.setWebViewClient(new WebViewClient());web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");}
 void cb(final String fn,final String json){runOnUiThread(new Runnable(){public void run(){web.evaluateJavascript("window."+fn+" && window."+fn+"("+json+")",null);}});}String esc(String s){return JSONObject.quote(s==null?"":s);}String now(){return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.CHINA).format(new Date());}
 public class Bridge{
  @JavascriptInterface public String getSettings(){try{JSONObject j=new JSONObject();j.put("baseUrl",sp.getString("base",DEF_BASE));j.put("model",sp.getString("model",DEF_MODEL));j.put("apiKey",sp.getString("key",""));j.put("remember",sp.getBoolean("remember",false));return j.toString();}catch(Exception e){return"{}";}}
  @JavascriptInterface public void saveSettings(String json){try{JSONObject j=new JSONObject(json);SharedPreferences.Editor e=sp.edit();e.putString("base",clean(j.optString("baseUrl",DEF_BASE)));e.putString("model",j.optString("model",DEF_MODEL));e.putBoolean("remember",j.optBoolean("remember",false));if(j.optBoolean("remember",false))e.putString("key",j.optString("apiKey",""));else e.remove("key");e.apply();}catch(Exception ignored){}}
  @JavascriptInterface public void requestModels(final String rid,final String base,final String key){new Thread(new Runnable(){public void run(){try{HttpURLConnection c=conn(clean(base)+"/v1/models","GET",key,null);String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("body",new JSONObject(body)).toString());}catch(Exception e){cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void generateText(final String rid,final String base,final String key,final String model,final String prompt,final String neg,final int n,final String ratio,final String quality){new Thread(new Runnable(){public void run(){try{JSONObject req=new JSONObject();req.put("model",model);req.put("prompt",promptPlus(prompt,ratio,quality));req.put("n",n);String size=sizeFor(ratio,quality);if(size.length()>0)req.put("size",size);if(neg!=null&&neg.trim().length()>0)req.put("negative_prompt",neg);HttpURLConnection c=conn(clean(base)+"/v1/images/generations","POST",key,"application/json");c.getOutputStream().write(req.toString().getBytes("UTF-8"));String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));ArrayList<Item> items=parseAndPersist(body);addHistory("文生图",prompt,items);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("items",itemsJson(items)).toString());}catch(Exception e){cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void pickImages(){Intent it=new Intent(Intent.ACTION_OPEN_DOCUMENT);it.setType("image/*");it.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);it.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(it,REQ_PICK);}
  @JavascriptInterface public void generateEdit(final String rid,final String base,final String key,final String model,final String prompt,final int n,final String ratio,final String quality){new Thread(new Runnable(){public void run(){try{if(selectedUris.size()==0)throw new Exception("请先选择参考图");String boundary="----Image2Studio"+System.currentTimeMillis();HttpURLConnection c=conn(clean(base)+"/v1/images/edits","POST",key,"multipart/form-data; boundary="+boundary);OutputStream out=c.getOutputStream();part(out,boundary,"model",model);part(out,boundary,"prompt",promptPlus(prompt,ratio,quality));part(out,boundary,"n",String.valueOf(n));String size=sizeFor(ratio,quality);if(size.length()>0)part(out,boundary,"size",size);for(int i=0;i<selectedUris.size();i++)filePart(out,boundary,"image","ref"+i+".png",selectedUris.get(i));out.write(("--"+boundary+"--\r\n").getBytes("UTF-8"));String body=readAll(c);if(c.getResponseCode()/100!=2)throw new Exception(err(body));ArrayList<Item> items=parseAndPersist(body);addHistory("图生图",prompt,items);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("items",itemsJson(items)).toString());}catch(Exception e){cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public String loadHistory(){return sp.getString("history","[]");}
  @JavascriptInterface public void clearHistory(){File[] fs=imgDir().listFiles();if(fs!=null)for(File f:fs)f.delete();sp.edit().remove("history").apply();}
  @JavascriptInterface public void saveCurrentToGallery(final String rid){new Thread(new Runnable(){public void run(){try{int ok=savePaths(currentPaths);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("saved",ok).toString());}catch(Exception e){cb("nativeResolve",errObj(rid,e));}}}).start();}
  @JavascriptInterface public void saveHistoryItemToGallery(final String rid,final String jsonPaths){new Thread(new Runnable(){public void run(){try{JSONArray a=new JSONArray(jsonPaths);ArrayList<String> ps=new ArrayList<String>();for(int i=0;i<a.length();i++)ps.add(a.optString(i));int ok=savePaths(ps);cb("nativeResolve",new JSONObject().put("id",rid).put("ok",true).put("saved",ok).toString());}catch(Exception e){cb("nativeResolve",errObj(rid,e));}}}).start();}
 }
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ_PICK&&c==RESULT_OK&&data!=null){selectedUris.clear();if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount()&&i<4;i++)selectedUris.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)selectedUris.add(data.getData());cb("onImagesPicked","{"+"\"count\":"+selectedUris.size()+"}");}}
 String clean(String s){if(s==null||s.trim().length()==0)s=DEF_BASE;s=s.trim();while(s.endsWith("/"))s=s.substring(0,s.length()-1);return s;}HttpURLConnection conn(String u,String m,String key,String type)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod(m);c.setConnectTimeout(20000);c.setReadTimeout(180000);c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Accept","application/json");if(type!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",type);}return c;}String readAll(HttpURLConnection c)throws Exception{InputStream is;try{is=c.getInputStream();}catch(Exception e){is=c.getErrorStream();}if(is==null)return"";BufferedReader br=new BufferedReader(new InputStreamReader(is,"UTF-8"));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line).append('\n');return sb.toString();}String err(String b){try{JSONObject j=new JSONObject(b);JSONObject e=j.optJSONObject("error");if(e!=null&&e.optString("message").length()>0)return e.optString("message");}catch(Exception ignored){}return b.length()>500?b.substring(0,500):b;}String errObj(String id,Exception e){try{return new JSONObject().put("id",id).put("ok",false).put("error",e.getMessage()).toString();}catch(Exception x){return"{\"ok\":false}";}}
 String promptPlus(String p,String r,String q){String e="";if(!"Auto".equals(r))e+=", "+r+" aspect ratio";if("4K".equals(q))e+=", true 4K, ultra detailed";return p+e;}String sizeFor(String r,String q){if(!"4K".equals(q))return"";if("16:9".equals(r))return"3840x2160";if("9:16".equals(r))return"2160x3840";if("1:1".equals(r))return"2880x2880";if("4:3".equals(r))return"3200x2400";if("3:4".equals(r))return"2400x3200";return"2880x2880";}
 void part(OutputStream o,String b,String n,String v)throws Exception{o.write(("--"+b+"\r\nContent-Disposition: form-data; name=\""+n+"\"\r\n\r\n"+v+"\r\n").getBytes("UTF-8"));}void filePart(OutputStream o,String b,String n,String f,Uri u)throws Exception{o.write(("--"+b+"\r\nContent-Disposition: form-data; name=\""+n+"\"; filename=\""+f+"\"\r\nContent-Type: image/png\r\n\r\n").getBytes("UTF-8"));InputStream in=getContentResolver().openInputStream(u);byte[] buf=new byte[8192];int len;while((len=in.read(buf))>0)o.write(buf,0,len);in.close();o.write("\r\n".getBytes("UTF-8"));}
 static class Item{String path,url;Item(String p,String u){path=p;url=u;}}File imgDir(){return new File(getFilesDir(),"images");}ArrayList<Item> parseAndPersist(String body)throws Exception{ArrayList<Item> out=new ArrayList<Item>();JSONObject j=new JSONObject(body);JSONArray a=j.optJSONArray("data");if(a==null)return out;imgDir().mkdirs();currentPaths.clear();for(int i=0;i<a.length();i++){JSONObject it=a.getJSONObject(i);String url=it.optString("url","");String b64=it.optString("b64_json","");if(b64.length()==0)b64=it.optString("b64","");Bitmap bm=null;if(url.length()>0)bm=BitmapFactory.decodeStream(new URL(url).openStream());else if(b64.length()>0){String raw=b64.startsWith("data:")?b64.substring(b64.indexOf(',')+1):b64;byte[] bytes=Base64.decode(raw,Base64.DEFAULT);bm=BitmapFactory.decodeByteArray(bytes,0,bytes.length);}if(bm!=null){File f=new File(imgDir(),"image2_"+System.currentTimeMillis()+"_"+i+".png");FileOutputStream fos=new FileOutputStream(f);bm.compress(Bitmap.CompressFormat.PNG,100,fos);fos.close();out.add(new Item(f.getAbsolutePath(),url));currentPaths.add(f.getAbsolutePath());}}return out;}JSONArray itemsJson(ArrayList<Item> items)throws Exception{JSONArray a=new JSONArray();for(Item it:items)a.put(new JSONObject().put("path",it.path).put("url",it.url).put("fileUrl","file://"+it.path));return a;}void addHistory(String mode,String prompt,ArrayList<Item> items)throws Exception{JSONArray old=new JSONArray(sp.getString("history","[]"));JSONObject o=new JSONObject();o.put("time",now());o.put("mode",mode);o.put("prompt",prompt);JSONArray ps=new JSONArray();for(Item it:items)ps.put(it.path);o.put("paths",ps);JSONArray n=new JSONArray();n.put(o);for(int i=0;i<old.length()&&i<19;i++)n.put(old.getJSONObject(i));sp.edit().putString("history",n.toString()).apply();}
 int savePaths(ArrayList<String> paths)throws Exception{int ok=0;for(String p:paths){Bitmap bm=BitmapFactory.decodeFile(p);if(bm==null)continue;ContentValues cv=new ContentValues();cv.put(MediaStore.Images.Media.DISPLAY_NAME,"Image2Studio_"+System.currentTimeMillis()+".png");cv.put(MediaStore.Images.Media.MIME_TYPE,"image/png");if(Build.VERSION.SDK_INT>=29)cv.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Image2Studio");Uri uri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,cv);if(uri==null)continue;OutputStream os=getContentResolver().openOutputStream(uri);bm.compress(Bitmap.CompressFormat.PNG,100,os);os.close();ok++;}return ok;}
}
